x-vy:
  anchors:
    CONTROLLERIMAGE: stage:controller2
    PARAMS: vydir:asi_ros1_sim
  subcompose:
    - name: compose:asi_ros2_sim
  
services:
  grid:
    network_mode: host
    environment:
      ROS_MASTER_URI: http://localhost:11311
  planner:
    network_mode: host
    environment:
      ROS_MASTER_URI: http://localhost:11311
  controller:
    command: >-
      bash -c "source install/local_setup.bash && cd src/ && ros2 run asi_ctrl map_ca &
        source install/local_setup.bash && cd src/ && ros2 run asi_ctrl cssmpc --ros-args --params-file /ros2_ws/cssmpc_configs/default_params.yaml"
    image: $CONTROLLERIMAGE
    network_mode: host
    environment:
      ROS_MASTER_URI: http://localhost:11311
    volumes:
      - read_only: true
        source: $PARAMS/vy/cssmpc_configs/default_params.yaml
        target: /ros2_ws/cssmpc_configs/default_params.yaml
        type: bind
  simulator:
    network_mode: host
    environment:
      ROS_MASTER_URI: http://localhost:11311
  rviz:
    command: rviz2 -d /rviz/asi_partners_sim_ros2.rviz
    network_mode: host
    environment:
      ROS_MASTER_URI: http://localhost:11311
  params:
#    command: ros2 -d /rviz/asi_partners_sim_ros2.rviz
    image: $PARAMSIMAGE
    network_mode: host
    privileged: true
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro

version: '3.2'
