x-vy:
  anchors:
    CONTROLLERIMAGE: stage:controller
  subcompose:
    - name: compose:asi_ros1_sim
  
services:
  controller:
    command: >-
      bash -c ". install/setup.bash && until rostopic list ; do sleep 1; done && sleep 3 && source devel/setup.bash && python3.6 polylines_asi.py & source devel/setup.bash && python3.6 cs_controller_asi_convex.py"
    image: $CONTROLLERIMAGE

version: '3.2'
