x-vy:
  anchors:
    CONTROLLERIMAGE: stage:controller2
  subcompose:
    - name: compose:asi_ros2_sim
  
services:
  grid:
    network_mode: host
    environment:
      ROS_MASTER_URI: http://localhost:11311
  planner:
    network_mode: host
    environment:
      ROS_MASTER_URI: http://localhost:11311
  controller:
    command: >-
      bash -c "source install/local_setup.bash && cd src/ && python3 polylines_asi.py & source install/local_setup.bash && cd src/ && python3 cs_controller_asi_convex.py"
    image: $CONTROLLERIMAGE
    network_mode: host
    environment:
      ROS_MASTER_URI: http://localhost:11311
  simulator:
    network_mode: host
    environment:
      ROS_MASTER_URI: http://localhost:11311
  rviz:
    command: rviz2 -d /rviz/asi_partners_sim_ros2.rviz
    network_mode: host
    environment:
      ROS_MASTER_URI: http://localhost:11311

version: '3.2'
