   /**:
     ros__parameters:
       max_speed: 20.0
       terminal_speed: -1.0
       horizon_length: 20
       time_step: 0.1
       throttle_min: -0.2
       throttle_max: 0.4
       delta_steer_min: -0.01
       delta_steer_max: 0.01
       delta_throttle_min: -0.2
       delta_throttle_max: 0.05
       Q_speed: 100.0
       Q_heading: 300.0
       Q_lateral: 30.0
       QN_speed: 1000.0
#       QN_heading: Q_heading * horizon_length
#       QN_lateral: max(Q_heading, Q_lateral) * horizon_length
       R_steer: 2.0
       R_throttle: 2.0

       width_cells: 120
       front_cells: 60
       back_cells: 60
       inertial_frame: true

       bound_ceiling: 20.0
       bound_length: 25.0
       bound_stride: 1.0
       obs_buffer: 1.5
       min_track_width: 6.0
       obs_method: 2

       odometry_topic: odometry_teleop
       command_topic: tbsg_cmd
       plan_topic: planned_path
       viz_topic: vizplan

       steering_gain: -1.2
       steer_min: -0.785
       steer_max: 0.785
       acceleration_gain: 10.0
