   /**:
     ros__parameters:
       max_speed: 20.0
       terminal_speed: -1.0
       horizon_length: 20
       time_step: 0.1
       throttle_min: -0.2
       throttle_max: 0.4
       delta_steer_min: -0.3
       delta_steer_max: 0.3
       delta_throttle_min: -0.2
       delta_throttle_max: 0.05
       Q_speed: 10.0
       Q_heading: 300.0
       Q_lateral: 30.0
       QN_speed: 0.0
#       QN_heading: Q_heading * horizon_length
#       QN_lateral: max(Q_heading, Q_lateral) * horizon_length
       R_steer: 2.0
       R_throttle: 2.0

       width_cells: 120
       front_cells: 60
       back_cells: 60
       inertial_frame: true

       odometry_topic: odometry_teleop
       command_topic: vcu_wrench
       plan_topic: planned_path
       viz_topic: vizplan

       steering_gain: -0.06
