/**:
  ros__parameters:
    width_cells: 50
    front_cells: 70
    back_cells: 10
    inertial_frame: false
    odometry_topic: odom_topic
    command_topic: vcu_wrench
    plan_topic: planned_path
    viz_topic: viz_plan
  