x-vy:
  anchors:
    DR: argument:Debug
    ROS2: argument:foxy
    CALIBRATION: definition:asi_boring_sim
    BORINGNODES: stage:asi_boring_sim
    RVIZFILES: vydir:boring_sim
    BAGFILE: directory:./bags
    PARAMS: vydir:cs-smpc
    CONTROLLERIMAGE: stage:controller2

services:
  nodes:
    command: >-
      bash -c ". /opt/ros/$ROS2/setup.bash && . install/setup.bash && (xterm &
        python3 ./install/share/boring_nodes/launch/ackermann_sim_launch.py /calibration.json &
        rviz2 -d /rviz/asi_partners_sim_ros2.rviz) &
        source install/local_setup.bash && cd src/ && ros2 run asi_ctrl map_ca -r __ns:='/ius0' --ros-args --params-file /ros2_ws/cssmpc_configs/default_params.yaml &
        source install/local_setup.bash && cd src/ && ros2 run asi_ctrl cssmpc -r __ns:='/ius0' --ros-args --params-file /ros2_ws/cssmpc_configs/default_params.yaml"
    image: $CONTROLLERIMAGE
    privileged: true
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${RVIZFILES}/rviz:/rviz
      - $CALIBRATION>calibration.json:/calibration.json:ro
      - read_only: true
        source: $PARAMS/cssmpc_configs/default_params.yaml
        target: /ros2_ws/cssmpc_configs/default_params.yaml
        type: bind

version: '3.2'
